name: Merge to Develop/Stage

on:
  push:
    branches:
      - develop
      - stage
      - master

      
jobs:
  merge:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/stage' ||
      github.ref == 'refs/heads/master' &&
      github.actor != secrets.ADMIN_USERNAME

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Merge to Target Branch
        run: |
          git fetch origin $GITHUB_REF
          git checkout $GITHUB_REF
          git merge --no-ff $GITHUB_HEAD_REF
          git push origin $GITHUB_REF
