name: Merge to Develop/Stage

on:
  push:
    branches:
      - develop
      - stage
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        continue-on-error: false

      - name: Build
        run: npm run build
        continue-on-error: false

      - name: Merge to Target Branch
        run: |
          git checkout origin/${{ github.event.pull_request.base.ref }}
          git merge --ff-only ${{ github.event.pull_request.head.ref }}
          git push origin ${{ github.event.pull_request.base.ref }}
