name: Merge to Any Branch

on:
  push:
    branches:
      - '*'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        continue-on-error: false

      - name: Build
        run: npm run build
        continue-on-error: false

      - name: Merge to Target Branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git merge --no-ff ${{ github.event.pull_request.base.ref }} -m "Merge pull request #${{ github.event.number }} from ${{ github.event.pull_request.head.ref }} into ${{ github.event.pull_request.base.ref }}"
          git push origin ${{ github.event.pull_request.head.ref }}

